### ISSUE TITLE
World map tile server might need to change

### ISSUE THREAD

**Issue by thibaultmol** [kauevestena/opensidewalkmap#1]
Hi, stumbled on your project. Noticed that the world view map on
https://kauevestena.github.io/opensidewalkmap/
seems to use a tile server that isn't going to be available anymore?
![image](https://github.com/kauevestena/opensidewalkmap/assets/1010226/d44bf4cf-698b-46ec-a1af-d5c1315c82d8)

(not sure if it's relevant: Maptiler has a generous freetier, not sponsored, i just know about it from MapComplete)

**Comment by kauevestena** [comment]
Thanks for the advice! I already noticed it and is because Stamen recently stopped offering the free tiles server: https://stamen.com/stamen-x-stadia-the-end-of-the-road-for-stamens-legacy-map-tiles/ 

Ever since thinking of a solution, I have been interested in implementing Protomaps or rendering myself up to level 5 or 6 that is what I need for this project...  But I still had no time, I think I will put default OSM in the middle time... (but's kinda weird, since it seems that you're entering openstreetmap.org haha)

**Comment by thibaultmol** [comment]
Since you're using Leaflet, you might be able to use Maptiler (vector maps instead of regular tiles). 
MapComplete is using that and their free tier is pretty generous apparently.
https://docs.maptiler.com/leaflet/

**Comment by kauevestena** [comment]
Sadly it doesn't seems like that =(

![image](https://github.com/kauevestena/opensidewalkmap/assets/1434036/f676bd01-9a74-4e48-bff2-5b9f1b56abb9)

**Comment by kauevestena** [comment]
Now this issue is solved, the solution was to use carto tiles, with their authorization
